### ISSUE TITLE
1.12 become ghost but appear normal after death

### ISSUE THREAD

**Issue by lag42** [Pyrofab/Dissolution#11]

**Comment by Pyrofab** [comment]
I would appreciate some details. Were you playing on a dedicated server ? Did you enable specific config options ? Does it happen with no other mods installed ?

**Comment by lag42** [comment]
it happens with no other mods installed and all you need to do is go to the nether and die, then you appear to respawn normally but you are a ghost that can't interact with the world and you don't appear transparent

**Comment by Pyrofab** [comment]
Thanks for the added information. I will try to fix it but it may take some time. In the meantime, you can quit and rejoin your world to fix it.

**Comment by Pyrofab** [comment]
Can you reproduce it reliably with the latest version ? I tried to do what you just said but everything works correctly.

**Comment by Pyrofab** [comment]
I guess the bug is fixed
