### ISSUE TITLE
1.12 - phantom items

### ISSUE THREAD

**Issue by Zygus42** [Pyrofab/Dissolution#12]
dissolution-0.4.2.2.jar

In a test I ran, I had on a pair of diamond boots and a diamond helmet.  When I returned to my body, it re-equipped those items for me, but it also left another set of them as items floating on the ground.  I was unable to pick these items up again, so it was as if they weren't really there, but I could see them clearly.

**Comment by Pyrofab** [comment]
Huh, never saw this bug through my testing. Looks like a clientside bug, you can make the phantom items go away by exiting and reentering your world / server. Shouldn't be too hard to fix.

**Comment by Pyrofab** [comment]
Fixed in v0.4.2.3
