### ISSUE TITLE
Crystallizer

### ISSUE THREAD

**Issue by Gromyown** [Pyrofab/Dissolution#13]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  MoreCommandsLoadingPlugin (MoreCommands-1.12-6.0.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 8/10/17 9:52 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at ladysnake.dissolution.common.tileentities.TileEntityCrystallizer.canSmelt(TileEntityCrystallizer.java:328)
	at ladysnake.dissolution.common.tileentities.TileEntityCrystallizer.func_73660_a(TileEntityCrystallizer.java:242)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ladysnake.dissolution.common.tileentities.TileEntityCrystallizer.canSmelt(TileEntityCrystallizer.java:328)
	at ladysnake.dissolution.common.tileentities.TileEntityCrystallizer.func_73660_a(TileEntityCrystallizer.java:242)

-- Block entity being ticked --
Details:
	Name: minecraft:dissolutiontileentitycrystallizer // ladysnake.dissolution.common.tileentities.TileEntityCrystallizer
	Block type: ID #296 (tile.crystallizer // ladysnake.dissolution.common.blocks.BlockCrystallizer)
	Block data value: 11 / 0xB / 0b1011
	Block location: World: (-886,64,3128), Chunk: (at 10,4,8 in -56,195; contains blocks -896,0,3120 to -881,255,3135), Region: (-2,6; contains chunks -64,192 to -33,223, blocks -1024,0,3072 to -513,255,3583)
	Actual block type: ID #296 (tile.crystallizer // ladysnake.dissolution.common.blocks.BlockCrystallizer)
	Actual block data value: 11 / 0xB / 0b1011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Gromyown'/353, l='world', x=-883.57, y=64.00, z=3128.39]]
	Chunk stats: ServerChunkCache: 733 Drop: 0
	Level seed: 3639922731245417344
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (152,64,256), Chunk: (at 8,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 115110240 game time, 1249217 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 153903 (now: false), thunder time: 36955 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1443195112 bytes (1376 MB) / 2383413248 bytes (2273 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xms2G -Xmx3G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443-universal.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443-universal.jar) 
	UCHIJAAAA	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	dailies{1.12-6} [Bailey's Dailies] (Baileys-Dailies-Mod-1.12.jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAA	movingworld{1.12-4.340} [Moving World] (movingworld-1.12-4.340-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-5.335-full.jar) 
	UCHIJAAAA	dissolution{0.4.2.3} [Dissolution] (dissolution-0.4.2.3.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	jaff{1.7_for_1.12} [Just a Few Fish] (JustAFewFish-1.7_for_1.12.jar) 
	UCHIJAAAA	mrnobody_morecommands{5.0} [MoreCommands] (MoreCommands-1.12-6.0.jar) 
	UCHIJAAAA	musiccraft{3.2.3} [MusicCraft] (MusicCraft-3.2.3.jar) 
	UCHIJAAAA	reptilemod{3.8.2} [Reptile Mod] (Reptile-1.12.jar) 
	UCHIJAAAA	simplesponge{3.5} [Simple Sponge] (Simple-Sponge-1.12.jar) 
	UCHIJAAAA	toroquest{1.11.2-5.1} [ToroQuest] (Toroquest-1.12.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  
MoreCommandsLoadingPlugin (MoreCommands-1.12-6.0.jar)
  com.mrnobody.morecommands.asm.transform.TransformBlockRailBase
  com.mrnobody.morecommands.asm.transform.TransformForgeHooks
  com.mrnobody.morecommands.asm.transform.TransformItemStack
  com.mrnobody.morecommands.asm.transform.TransformStyle
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Gromyown'/353, l='world', x=-883.57, y=64.00, z=3128.39]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Pyrofab** [comment]
Well, the crystallizer will be completely rewrote next update so that should fix the issue... In the meantime, I will try to get a small fix out.

**Comment by Pyrofab** [comment]
Does it happen under special circumstances ? It works fine for me.
