### ISSUE TITLE
[feature request] ingame information on certain blocks

### ISSUE THREAD

**Issue by Zygus42** [Pyrofab/Dissolution#14]
I notice that the Soul Extractor has a JEI info tab, which is great, but would it be possible to get the same done for:
1) Soul Anchor
2) Mercury Candle
3) Sulfur Candle

As I have no idea what these do and couldn't find these on the WIki either.  Thank you for a great mod !

**Comment by Pyrofab** [comment]
The soul anchor is mentioned in the JEI tab of the Mercurius waystone. It's a fancy portal for souls. As the item cannot be obtained in survival, I did not see the need for a JEI tab on it's own.
The candles were an experimentation that will be removed next update. They were intended to be ways of changing your corporeal status in an area.

**Comment by Pyrofab** [comment]
All those blocks have been removed, new ones have been documented. Tell me if there isn't enough info !
