### ISSUE TITLE
[Question] What are Mercury lakes for ?

### ISSUE THREAD

**Issue by Zygus42** [Pyrofab/Dissolution#15]
I don't appear to be able to interact with these lakes at all, and can't find any recipes that need Mercury.  Do these have a use ?

**Comment by Pyrofab** [comment]
They will be used for crafting later on. For now, they can be used as yet another way of getting a new body. (don't question the logic)

**Comment by Pyrofab** [comment]
Mercury lakes are removed in 0.5
