### ISSUE TITLE
Dissolution forcing hidden health bar to be shown (mod compatibility issue)

### ISSUE THREAD

**Issue by Thyriel** [Pyrofab/Dissolution#17]
Not sure why as your mod shouldn't affect living players much, but it seems your mod is somehow forcing the health bar to be shown even when other mods hide it. ("First Aid" mod for example)

**Comment by Pyrofab** [comment]
I think I already fixed it for the next update. I will need to double-check that though.

**Comment by Pyrofab** [comment]
I tested with latest version of both dissolution and first aid mod, I don't see that issue occuring.
