### ISSUE TITLE
1.11.2 - Cannot respawn after dying on server

### ISSUE THREAD

**Issue by Febilian** [Pyrofab/Dissolution#2]
https://gist.github.com/Febilian/48cf0bd6be539ab861df93115b767365

If a player dies, the respawn button does nothing at all in a recently created world, and the log throws an error related to this mod. I didn't have any config options changed from the defaults.

EDIT: By this I mean that you basically get stuck in the respawn menu indefinitely.

**Comment by Pyrofab** [comment]
I got this issue during testing but I was sure I corrected it before launch... Alright I will try to correct it before tomorrow.

**Comment by Pyrofab** [comment]
Which Forge version did you use ? For some reason your game misses a vanilla minecraft method. Also, can you reproduce it without other mods ?

**Comment by Febilian** [comment]
Forge version 13.20.0.2310

I'll have to test without other mods at some point when I have the time.

**Comment by Febilian** [comment]
I guess it might be related to the other mods being used, as this did not happen with literally only Dissolution and Forge installed.

I don't know which other mod was breaking it, I'm afraid, and I don't have the time to test them one at a time. I'm sorry, I know that isn't very helpful.

**Comment by Pyrofab** [comment]
Do you think you could retry with the latest 1.11.2 version ? I fixed quite a lot of bugs since then.
