### ISSUE TITLE
crash upon using a separator

### ISSUE THREAD

**Issue by lag42** [Pyrofab/Dissolution#21]
crash log here:
https://gist.github.com/lag42/a7756825eedfdd2b5a93b8d322a95fd4

**Comment by Pyrofab** [comment]
Looking at that crash report, it doesn't seem possible. Did that happen under specific circumstances ?

**Comment by lag42** [comment]
It might not have been a valid recipe, did you try doing it with an empty one?

**Comment by Pyrofab** [comment]
Oh. OK. I really need to try more things sometimes.

**Comment by Pyrofab** [comment]
Fixed in 0.5.1

**Comment by lag42** [comment]
Can you upload 0.5.1 as a hotfix or do you need to fix something else too

**Comment by Pyrofab** [comment]
I generally upload the files before closing issues. In this case, curseforge was late by a few hours.
