### ISSUE TITLE
Alternative flight modes not working [1.11.2]

### ISSUE THREAD

**Issue by daPoseidonGuy** [Pyrofab/Dissolution#25]
No matter what flight mode is specified in the config, dissolution uses the default
On 1.11.2
Mod version 0.4.2.3
Forge forge-1.11.2-13.20.1.2530
On dedicated server

**Comment by Pyrofab** [comment]
The 1.11 version isn't really supported anymore but I'll try to upload a fix

**Comment by Pyrofab** [comment]
Ah, that's probably because the config for flight mode is client side. It's actually the same in the latest version. You need to sync configs between client and server yourself.

**Comment by daPoseidonGuy** [comment]
I was pretty sure I had the settings set the same in both
I noticed there were actually two places in the config to input desired flight mode.

**Comment by Pyrofab** [comment]
Ah yes, the config file isn't cleaned up every version so properties get duplicated when I move them. I'm currently trying to fix all that. Next version should have config syncing by the way.
