### ISSUE TITLE
[1.12.2] Server Crashes due to unable to find I18N

### ISSUE THREAD

**Issue by Joshwoo70** [Pyrofab/Dissolution#26]
Crashlog: https://gist.github.com/Joshwoo70/409618b8c6cb295dff242cbab78319d2

**Comment by Joshwoo70** [comment]
Btw. This is from BTM Moon server which you have registered for a booth afaik.

**Comment by Pyrofab** [comment]
Yup, thanks for the crash report ! I'll fix it as soon as possible.

**Comment by lag42** [comment]
Somewhat unrelated, but what's btm moon

**Comment by Pyrofab** [comment]
Fixed in 0.5.3.
@lag42 Better Than Minecon Moon:tm: is a minecraft in-game convention that takes place in a few days.
(more information on http://btm.mcft.net/moon/)
