### ISSUE TITLE
[feature request] please add info overlays to each item

### ISSUE THREAD

**Issue by Zygus42** [Pyrofab/Dissolution#4]
Please add info overlays to each item, so that if you're looking at an item in-game, such as "Soul Extractor" for example, you would have a clue as to what it does and how it works.  As it stands, on my server, people will look at it, not know what it does and never make one.

**Comment by Pyrofab** [comment]
Actually, the main reason I did not add descriptive tooltips are that these crafting mechanics will get revamped at some point and are already being phased out in favor of more interesting respawn options. I will still include tooltips in the next update. Or did you mean something else with "overlay" ?

**Comment by Zygus42** [comment]
Tooltips are just fine.  Some mods are using other methods now which are much the same, such as info tabs through JEI or a book that describes stuff in more detail.  Just need something.

**Comment by Pyrofab** [comment]
Added in 0.4.2 update. I finally settled for JEI descriptions as tooltips would be either too long or not descriptive enough. I will probably only do them for very important blocks and items though, the rest will be documented in the wiki.
