### ISSUE TITLE
[feature request] ability to pass through blocks above death point

### ISSUE THREAD

**Issue by Zygus42** [Pyrofab/Dissolution#5]
Currently you get to your death site and if you died underground you have no way of getting back to it.  Would be great if you could sink through the ground to it.

**Comment by Zygus42** [comment]
Just realized that the death site means nothing in your mod as you have to go back to 0,0.  As we have another mod preserving our items at the death site, would it be possible to maybe set in the config that the death site is the place to go to respawn instead of 0,0 ?

**Comment by Pyrofab** [comment]
You can change the config to always create a corpse where you died, that will act as a respawn point and a gravestone at the same time. Next update, there will also be the config to disable their decay, so I don't think adding a permanent respawn point where you die would be quite useful.
Sinking through the ground could be a good idea, but note that if you don't stop this ability at the right time, you will end up in the void.

**Comment by Zygus42** [comment]
Ah, ok - was using a different mod to create a gravestone with your items in it.

I like the being a ghost and having to do a corpse run - is a good compromise between having death be really nasty (default Minecraft) and really trivial (if you just set it so you don't lose your gear at all when you die).

Usually if you get to where you died, and if it was underground you could dig straight down - you can't as a ghost.  So, either:
1) need a method to sink downwards, perhaps only to the same y coord as the corpse, or
2) the corpse needs to be at ground level, or 
3) you need to be able to break the blocks directly above your corpse, or 
4) the depth wouldn't matter if the death spot counted as the resurrection point instead of 0,0, or
5) .....

**Comment by Pyrofab** [comment]
I kinda added that in the 0.4.2 update, however it will get reworked as I'm not happy with it in the current state (but I did not want to delay other important issues). If you want to use it, you can enable it in the config.

**Comment by Zygus42** [comment]
I turned on B:enableSoulDash=true, but it didn't work particularly well.  It didn't work a bunch of times, and then it did and I dropped into the world for a few blocks and was stuck there.  It certainly did not help with the 2 major problems with the mod:

1) my body is underground because that's where I died, but my ghost is above ground, as I can't get back down to where my body is and I can't tunnel because I'm in ghost form.

2) my ghost is back in my home base because that's where my bind point is, and I can't get out of my building to get back to my body, as I can't pass through the walls or doors.

**Comment by Pyrofab** [comment]
I know, it's not very functional right now, I will rewrite it at the same time as the possession mechanic. The soul dash puts you in spectator mode for a few seconds, allowing you to move through blocks. That will let you exit your house. You can technically use it to go through any obstacle, you just need to wait for the cooldown to go away (10s or something like that)

**Comment by Pyrofab** [comment]
Latest additions should have solved this issue.
