### ISSUE TITLE
[Bug] Fire immunity is carried after respawn

### ISSUE THREAD

**Issue by KingEdward9830** [Pyrofab/Dissolution#8]
With nether respawn on and everything else default, after returning to life I was immune to lava and fire damage without fire resistance effect. However mobs and fall damage still hurt me. I have yet to try this with any other config options.

**Comment by Pyrofab** [comment]
This should not be dependant on the nether respawn, I have probably forgot to revert some player properties.

**Comment by Pyrofab** [comment]
Maybe I solved the issue while doing something else, I could not reproduce it in the latest dev version. It should be out soon.

**Comment by KingEdward9830** [comment]
This is probably the main bug that's stopping me from wanting to play the mod in a survival world, so I hope you did.
