### ISSUE TITLE
[Bug] Corpses only store loot with scarab of eternity

### ISSUE THREAD

**Issue by KingEdward9830** [Pyrofab/Dissolution#9]
Long story short: corpses will ONLY store your loot if you have a Scarab of Eternity in your inventory, regardless of the WoWLikeRespawn config.

**Comment by Pyrofab** [comment]
Stupid oversight on my part indeed. By the way, could you use descriptive titles ? I really appreciate the help but if I have a list of 10 reports that say "there is a bug", it makes things unnecessarily complicated.

**Comment by Pyrofab** [comment]
Fixed in 0.4.2
